base_link: 'base_link'
gripper:
  #The end effector name for grasping
  end_effector_name: 'gripper'

  # Gripper joints
  joints: ['gripper_finger1_joint', 'gripper_finger2_joint']

  #Posture of grippers before grasping
  pregrasp_posture: [0.0] #open
  pregrasp_time_from_start: 4.0
  grasp_posture: [0.407] #close .45<0.451<.452, max value is 0.8040
  grasp_time_from_start: 4.0
  postplace_time_from_start: 4.0

  # Desired pose from end effector to grasp [x, y, z] + [R, P, Y]
  grasp_pose_to_eef: [-0.12, 0.0, 0.0]
  grasp_pose_to_eef_rotation: [0.0, 0.0, 0.0]
  end_effector_parent_link: 'ee_link'
