mobile_base:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

  pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: pitch_joint

  yaw_position_controller:
    type: position_controllers/JointPositionController
    joint:  yaw_joint
